### ISSUE TITLE
Idk, it just crashed....

### ISSUE THREAD

**Issue by Rioluking1991** [X-Hax/sa_tools#271] opened 2024-10-06 21:24 UTC
Program: Texture Editor
Build Date: 05/28/2022 17:09:08
OS Version: Microsoft Windows NT 10.0.19045.0
Log:
Texture Editor: New log entry on 06/10/2024 06:23:54 p. m.
Build date:05/28/2022 17:09:08
VrSharp.TextureNotInitalizedException: Cannot access this property as the texture is not initalized.
   at VrSharp.VrTextureEncoder.set_GlobalIndex(UInt32 value) in C:\Programs\sa_tools\Libraries\VrSharp\Core\VrTextureEncoder.cs:line 71
   at TextureEditor.MainForm.EncodeGVR(GvrTextureInfo tex) in C:\Programs\sa_tools\TextureEditor\MainForm.cs:line 618
   at TextureEditor.MainForm.SaveTextures() in C:\Programs\sa_tools\TextureEditor\MainForm.cs:line 653
   at TextureEditor.MainForm.MainForm_FormClosing(Object sender, FormClosingEventArgs e) in C:\Programs\sa_tools\TextureEditor\MainForm.cs:line 1615
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.RaiseFormClosingOnAppExit()
   at System.Windows.Forms.Application.Exit(CancelEventArgs e)
   at System.Windows.Forms.Application.Exit()
   at TextureEditor.MainForm.Application_ThreadException(Object sender, ThreadExceptionEventArgs e) in C:\Programs\sa_tools\TextureEditor\MainForm.cs:line 58
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.ControlNativeWindow.OnThreadException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
   at Interop.User32.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at TextureEditor.Program.Main(String[] args) in C:\Programs\sa_tools\TextureEditor\Program.cs:line 24

**Comment by PiKeyAr** [comment] 2024-10-07 02:48
Duplicate of #267

**Closed by PiKeyAr** 2024-10-07 02:48 UTC
