### ISSUE TITLE
SAMLD.dll files get deleted by my comuter and I can't copy them back.

### ISSUE THREAD

**Issue by Langtanium** [X-Hax/sa_tools#208] opened 2022-04-07 00:36 UTC

**Comment by Samuel555v** [comment] 2022-05-09 10:36
That's not an issue caused by sa tools so it doesnt belong in here, but either way what you need to do is make a folder, then make an exclusion to that folder in your anti virus. (if you don't have an anti virus then in windows defender). then download it again and put the files into that folder. since that folder is exclusioned, your anti-virus/windows defender won't delete it.

**Comment by Shadowth117** [comment] 2022-05-26 07:06
Closing this since it's not a valid issue.

**Closed by Shadowth117** 2022-05-26 07:06 UTC
Labels: invalid
